[storyline.bartolomeu]
id = "bartolomeu"
dir = "Bartolomeu"

[storyline.bartolomeu.tags]
beta = true

[storyline.bartolomeu.start]
location = "PoPrince_Port"
port = "PoPrince_Port"
model = "GypsyCaptn_2"
first_name = "Bartolomeu"
last_name = "o Portugues"
nation = "portugal"
player_type = "social_climber"
difficulty = "seadog"
pirate_flag = 4
personal_flag = 8

[storyline.bartolomeu.start.editable]
difficulty = true

[storyline.bartolomeu.start.date]
hour = 9
min = 17
sec = 42
day = 22
month = 7
year = 1660

[storyline.bartolomeu.variables]
ISLA_DE_MUERTE = -1
BART_PUZZLES = 1
START_MIN_LEVEL = 1
